language: cpp
git:
    depth: 50
    submodules: true
exclude:
    - if: branch = continous
jobs:
    include:
    - stage: build
      name: Build for x86 MSVC on Windows
      cache: ccache
      os: windows
      language: cpp
      before_script:
        - choco install -y visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64";
      script:
        - mkdir -p build && cd build
        - cmake -G "Visual Studio 15 2017" -A Win32 -DCMAKE_BUILD_TYPE=Release ../
        - cmake --build . --config Release
        - cd ..
      before_deploy:
        - git config --local user.name "laper32"
        - git config --local user.email "laper32@outlook.com"
        - export TRAVIS_TAG=continuous
        - git remote add travis-deploy-public https://${GITHUB_TOKEN}@github.com/laper32/QuestSystem.git
        - git tag --delete ${TRAVIS_TAG} || echo "tag not exists..."
        - git push travis-deploy-public --delete ${TRAVIS_TAG} || echo "remote tag not exists..."
        - git tag --force ${TRAVIS_TAG}
        - git push travis-deploy-public --tags --force
    deploy:
        provider: releases
        api_key: ${GITHUB_TOKEN}
        file:
            - build/src/Release/QuestSystem.ext.2.csgo.dll
        on:
            branch: master
            repo: laper32/QuestSystem
        overwrite: true
        skip_cleanup: true
        prerelease: true